# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b613534953179a14d548d77bd9c15df76bd12deeac6921b322c0fc504333fa13762d814a4f5ab3eaeb8f13a12d1ba456273ad0ab6ea75713b299e2225dbfeae

test:
  secret_key_base: c05c2a771c52a85da7b5758d84a3d3c44ea924a63411e1f41eef66a1e50f718ae77896c14f3df921f18b0b3f90c98c1aadb902245c730497561591d93987373e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
